<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use App\Models\profile;
use App\Models\accounts;

class ProfileSeeder extends Seeder
{
 /**
  * Run the database seeds.
  *
  * @return void
  */
 public function run()
 {
  DB::table('profile')->delete();
  $np_user = DB::table('accounts')->pluck('np');

  $profile = [
['id' => ' 1', 'foto' =>	'default-avatar.png', 'np_user' => '7197'	, 'nama' => 'Herman Maulana Yusup' , 'email' => 'hermanmaulanay@gmail.com' , 'tgl_lahir' => '1984-05-12', 'alamat' => 'Perum permata nirwana, puseurjaya, Telukjambe timur, Karawang' , 'contact' => '085779777971' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '11', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 2', 'foto' =>	'default-avatar.png', 'np_user' => '7198'	, 'nama' => 'Nunung Nurasiah' , 'email' => 'Rinakhoerunnissa 16@gmail.com' , 'tgl_lahir' => '1980-03-22', 'alamat' => 'Sukajaya 2 Rt12/05 Pinayungan Telukjambe Timur Karawang 41361' , 'contact' => '085719894575' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 3', 'foto' =>	'default-avatar.png', 'np_user' => '7199'	, 'nama' => 'Riska Kartika Sari' , 'email' => 'riska.kartikasari@peruri.co.id ' , 'tgl_lahir' => '1987-08-25', 'alamat' => 'Jl.suriadipati ko.poponcol kidul RT 01RW 01 no.13 Kel.karawang kulon kec.karawang barat 41311  ' , 'contact' => '081311003785' , 'id_seksi' => '2', 'id_unit' => '1', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 4', 'foto' =>	'default-avatar.png', 'np_user' => '7202'	, 'nama' => 'Kartika Meta' , 'email' => 'Kartika.kurniasih@peruri.co.id' , 'tgl_lahir' => '1984-03-23', 'alamat' => 'Babakan Rt 004 Rw 001 No 23 Puseurjaya Teluk Jambe Timur Karawang Jawa Barat ' , 'contact' => '081218427727' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '22', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 5', 'foto' =>	'default-avatar.png', 'np_user' => '7205'	, 'nama' => 'Wawan Kurnawan' , 'email' => 'pilotwawan1@gmail.com' , 'tgl_lahir' => '1984-04-04', 'alamat' => 'Ds. Balongsari RT 05/02 Kec. Rawamerta Kab. Karawang' , 'contact' => '085714149002' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '11', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 6', 'foto' =>	'default-avatar.png', 'np_user' => '7206'	, 'nama' => 'Eddy rismanto' , 'email' => 'Eddoy_seluler@yahoo.co.id' , 'tgl_lahir' => '1986-03-15', 'alamat' => 'Perum.Nuansa tradisi residance blok A.03/no17 .kondang jaya .Karawang timur  ' , 'contact' => '085710859953' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 7', 'foto' =>	'default-avatar.png', 'np_user' => '7418'	, 'nama' => 'Muridin Akbar' , 'email' => 'azighah@gmail.com' , 'tgl_lahir' => '1984-03-20', 'alamat' => 'Perumahan Grand Mutiara Village jalan ronggo waluyo Blok Bk 12 A Rt 05 / Rw 09 kel. Sirnabaya kecamatan Telukjambe Timur Kab. Karawang 41361' , 'contact' => '081213192327' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '16', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 8', 'foto' =>	'default-avatar.png', 'np_user' => '7423'	, 'nama' => 'Heni Suhaeni' , 'email' => 'henisuhaeni7423@gmail.com' , 'tgl_lahir' => '1982-09-25', 'alamat' => 'Puri Teluk Jambe Blok B14 no 11' , 'contact' => '089688027256' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	
['id' => ' 9', 'foto' =>	'default-avatar.png', 'np_user' => '7426'	, 'nama' => 'Aris Hudin' , 'email' => 'aris.hudin92@gmail.com' , 'tgl_lahir' => '1992-01-17', 'alamat' => 'Perum Green Harmony Residence Blok B3 No 3 Desa Pasirjengkol Kec. Majalaya' , 'contact' => '087736932212' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '8 ', 'updated_at' => now(), 'created_at' => now()], 
['id' => '10', 'foto' =>	'default-avatar.png', 'np_user' => '7437'	, 'nama' => 'Sandi Pratama' , 'email' => 'Ndiepratama.sp@gmail.com' , 'tgl_lahir' => '1992-01-23', 'alamat' => 'Perum griya mas lestari blok h5 no 39 Kel kondang jaya , kec karawang timur , Jawa barat' , 'contact' => '089699882051' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],  
['id' => '11', 'foto' =>	'default-avatar.png', 'np_user' => '7442'	, 'nama' => 'Fabby Frazasti Fridyan' , 'email' => 'fabbyfrazastifridyan@gmail.com ' , 'tgl_lahir' => '1990-05-11', 'alamat' => 'Perum kandiwa 2 blok H no 4 desa duren kec.klari karawang ' , 'contact' => '081294710543 / 081617937313  ' , 'id_seksi' => '2', 'id_unit' => '5', 'id_station' => '9 ', 'updated_at' => now(), 'created_at' => now()],  
['id' => '12', 'foto' =>	'default-avatar.png', 'np_user' => '7443'	, 'nama' => 'Agus Nurkomara' , 'email' => 'dd' , 'tgl_lahir' => '1985-06-01', 'alamat' => 'dd' , 'contact' => '123 ' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '12', 'updated_at' => now(), 'created_at' => now()],
['id' => '13', 'foto' =>	'default-avatar.png', 'np_user' => 'G752'	, 'nama' => 'Cindy Kania Aprillia' , 'email' => 'cindydo124@gmail.com' , 'tgl_lahir' => '1999-04-24', 'alamat' => 'Perum Griya Indah blok E.4 / 29 Rt/Rw, 017/ 005 Desa. Parungmulya Kec. Ciampel Kab. Karawang kode pos.41361' , 'contact' => '082292136752 / 085353172223  ' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '14', 'foto' =>	'default-avatar.png', 'np_user' => 'G763'	, 'nama' => 'Sri Rahayu' , 'email' => 'Rahayu9703@gmail.com' , 'tgl_lahir' => '1997-12-03', 'alamat' => 'Kp. Suka mulya rt. 002/ rw. 019 kel.  Karawang wetan kec.  Karawang timur ' , 'contact' => '0895369274624' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],
['id' => '15', 'foto' =>	'default-avatar.png', 'np_user' => 'H006'	, 'nama' => 'Siti Imaroh Nurfirdha Vamela' , 'email' => 'sitiimaroh98@gmail.com' , 'tgl_lahir' => '1998-03-02', 'alamat' => 'Perumnas BTJ blok F5' , 'contact' => '085730999598' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '16', 'foto' =>	'default-avatar.png', 'np_user' => 'H066'	, 'nama' => 'Syaiful Harisudin' , 'email' => 'syaifulhrs@gmail.com' , 'tgl_lahir' => '2000-09-22', 'alamat' => 'Perumahan Puri Telukjambe Rt/Rw 08/06 blok B1 no. 22 Ds. Sinarbaya Kec. Telukjambe timur Kab. Karawang  ' , 'contact' => '081296727236' , 'id_seksi' => '2', 'id_unit' => '5', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '17', 'foto' =>	'default-avatar.png', 'np_user' => 'H109'	, 'nama' => 'Wilda Nul`aini Salsabila' , 'email' => ' Wildasalsabila63@gmail.com' , 'tgl_lahir' => '1900-01-01', 'alamat' => ' Perumahan Puri Teluk Jambe Blok B 10/38 RT 06 RW 06 Ds.Sirnabaya ,Teluk Jambe Timur 41361 ' , 'contact' => '087776146084' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '18', 'foto' =>	'default-avatar.png', 'np_user' => 'H114'	, 'nama' => 'Dinda Anandita Faustina' , 'email' => 'd.anandita117@gmail.com' , 'tgl_lahir' => '1999-11-17', 'alamat' => 'GG. Sirnaraga 2, Dusun Sukatani, Desa Pinayungan, Kec. Teluk Jambe Timur (Kosan Bpk. Dedi) ' , 'contact' => '081290696980' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '19', 'foto' =>	'default-avatar.png', 'np_user' => 'H119'	, 'nama' => 'Yessi Dewi Nastiti' , 'email' => 'yessidewi23@gmail.com' , 'tgl_lahir' => '1996-05-23', 'alamat' => 'Perum Puri Telukjambe Blok C20 No.12  ' , 'contact' => '085703070219' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '20', 'foto' =>	'default-avatar.png', 'np_user' => 'H123'	, 'nama' => 'Ade Muhammad Irfan Zidny' , 'email' => 'amzidny@gmail.com' , 'tgl_lahir' => '1999-09-30', 'alamat' => 'Perumahan griya indah ' , 'contact' => '087776332208' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()], 
['id' => '21', 'foto' =>	'default-avatar.png', 'np_user' => 'H130'	, 'nama' => 'Nur Aprilianingsih' , 'email' => 'nurapriliani6@gmail.com' , 'tgl_lahir' => '1997-04-01', 'alamat' => 'Perum Mahkota Regency, Blok L3 no 2, Sirnabaya, Teluk Jambe Timur, Karawang  ' , 'contact' => '085601856101' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '22', 'foto' =>	'default-avatar.png', 'np_user' => 'H186'	, 'nama' => 'Indah Oktora Paramita' , 'email' => 'opeindah@gmail.com' , 'tgl_lahir' => '1998-10-31', 'alamat' => 'Dusun krajan 1 Rt/Rw 009/003 Ds. Talagasari Kec. Telagasari Kab. Karawang 41381 ' , 'contact' => '081282229247' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],
['id' => '23', 'foto' =>	'default-avatar.png', 'np_user' => 'H190'	, 'nama' => 'Fifin Fitria Anggraeni' , 'email' => 'fifinfitria6@gmail.com' , 'tgl_lahir' => '1999-01-24', 'alamat' => 'ss' , 'contact' => '082117376085' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '24', 'foto' =>	'default-avatar.png', 'np_user' => 'H191'	, 'nama' => 'Dewi Nurhikmawati' , 'email' => 'dewi.nurhikmawati2807@gmail.com' , 'tgl_lahir' => '2000-04-07', 'alamat' => 'Perum puri telukjambe blok b1 no51 ' , 'contact' => '081804840621' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '25', 'foto' =>	'default-avatar.png', 'np_user' => 'H192'	, 'nama' => 'Lisa Herlina' , 'email' => 'lisaaherln@gmail.com' , 'tgl_lahir' => '1999-11-01', 'alamat' => 'Dusun Sukawargi No.166 RT 007/003  ' , 'contact' => '087820757576' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '26', 'foto' =>	'default-avatar.png', 'np_user' => 'H193'	, 'nama' => 'Dinda Amelia' , 'email' => 'dindaamelia83@gmail.com' , 'tgl_lahir' => '1998-12-12', 'alamat' => 'Rt/02 Rw/01 desa walahar kec. Klari, Karawang  ' , 'contact' => '08871226173' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '27', 'foto' =>	'default-avatar.png', 'np_user' => 'H194'	, 'nama' => 'Lustanti Yuli Asih' , 'email' => 'lustantiyulia1234@gmail.com' , 'tgl_lahir' => '2000-07-08', 'alamat' => 'Perumahan Puri Telukjambe Blok A9 no 19' , 'contact' => '083862315072' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '28', 'foto' =>	'default-avatar.png', 'np_user' => 'H196'	, 'nama' => 'Ine Febrianti' , 'email' => 'febriantiine1@gmail.com' , 'tgl_lahir' => '2000-03-08', 'alamat' => 'Jl.Raya Peruri Perumahan Griya Indah blok C2 no 57A Karawang Jawa Barat' , 'contact' => '085321795933' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '29', 'foto' =>	'default-avatar.png', 'np_user' => 'H198'	, 'nama' => 'Nisa Madani' , 'email' => 'nisamadani99@gmail.com' , 'tgl_lahir' => '1999-04-06', 'alamat' => 'Puri Teluk Jambe Blok C 20 No.12' , 'contact' => '081381996133' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '30', 'foto' =>	'default-avatar.png', 'np_user' => 'H199'	, 'nama' => 'Delia Octriane' , 'email' => 'deliaoctriane12@gmail.com' , 'tgl_lahir' => '2000-10-12', 'alamat' => 'Perum Puri Telukjambe blok A9 no 19' , 'contact' => '085920620791' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '31', 'foto' =>	'default-avatar.png', 'np_user' => 'I402'	, 'nama' => 'Delia Harun' , 'email' => 'deliaharun96@gmail.com' , 'tgl_lahir' => '1998-08-15', 'alamat' => 'perum griya indah blok K2, ciampel, karawang' , 'contact' => '085819088979' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '32', 'foto' =>	'default-avatar.png', 'np_user' => 'I403'	, 'nama' => 'Dian Oktaviani' , 'email' => 'dian.oktaviani051@gmail.com' , 'tgl_lahir' => '2000-10-05', 'alamat' => 'Perum Griya Indah Blok M1 nomer 32 Parung Mulya, Ciampel, Karawang  ' , 'contact' => '0895353065699' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '33', 'foto' =>	'default-avatar.png', 'np_user' => 'I404'	, 'nama' => 'DINA APRILIANTI' , 'email' => 'apriliantidina8@gmail.com' , 'tgl_lahir' => '1996-04-14', 'alamat' => 'Perumahan Griya Indah Blok F4/08 RT17/RW05 Parungmulya, Ciampel, Karawang ' , 'contact' => '081388314497' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '34', 'foto' =>	'default-avatar.png', 'np_user' => 'I405'	, 'nama' => 'Fitri Setyorini' , 'email' => 'fitrisetyorini18@gmail.com' , 'tgl_lahir' => '1996-06-18', 'alamat' => 'Kos Gubug Mesem A2, No.17 Perum Griya Indah, Ciampel,Karawang' , 'contact' => '081381046623' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '35', 'foto' =>	'default-avatar.png', 'np_user' => 'I406'	, 'nama' => 'Karlina Ibrahim' , 'email' => 'Karlinaibrahim1604@gmail.com' , 'tgl_lahir' => '1997-04-16', 'alamat' => 'Perum Griya Indah Blok A2 No 17 RT 10 RW 01 Desa Parungmulya Kec.Ciampel Kab. Karawang 41363' , 'contact' => '081255117738' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],  
['id' => '36', 'foto' =>	'default-avatar.png', 'np_user' => 'I407'	, 'nama' => 'Khairunnisa Hikmayati' , 'email' => 'khikmayati@gmail.com' , 'tgl_lahir' => '1999-01-03', 'alamat' => 'Jl Kalijaya Puseurjaya No.70 RT/RW 011/002 Desa Sukaluyu  ' , 'contact' => '082210345527' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '37', 'foto' =>	'default-avatar.png', 'np_user' => 'I409'	, 'nama' => 'Mia Listiana' , 'email' => 'mialistiana29@gmail.com' , 'tgl_lahir' => '1996-09-29', 'alamat' => 'Perum griya indah blok f4/08, RT/RW. 17/05 Ds. Parungmulya kec. Ciampel Karawang' , 'contact' => '089650640731' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],  
['id' => '38', 'foto' =>	'default-avatar.png', 'np_user' => 'I420'	, 'nama' => 'Agus Aziz' , 'email' => 'Agusbungsubule@gmail.com' , 'tgl_lahir' => '1997-12-17', 'alamat' => 'Blok rabu Rt 07 RW 03 DESA LEUWILAJA KECAMATAN SINDANGWANGI KABUPATEN MAJALENGKA' , 'contact' => '089631394613' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()], 
['id' => '39', 'foto' =>	'default-avatar.png', 'np_user' => 'I421'	, 'nama' => 'Avrila Wiranti' , 'email' => 'avrilawiranti99@gmail.com' , 'tgl_lahir' => '1999-04-09', 'alamat' => 'Sukaluyu, Teluk Jambe Timur ' , 'contact' => '085600150852' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],  
['id' => '40', 'foto' =>	'default-avatar.png', 'np_user' => 'I423'	, 'nama' => 'Citra afrida sari' , 'email' => 'Citraafridasari1002@gmail.com' , 'tgl_lahir' => '1998-02-10', 'alamat' => 'Perum griya indah blok L1 no 35 parung mulya, ciampel, karawang  ' , 'contact' => '082244419238' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '41', 'foto' =>	'default-avatar.png', 'np_user' => 'I424'	, 'nama' => 'Daffa Pratama Putra' , 'email' => 'daffapratamaputra157@gmail.com ' , 'tgl_lahir' => '1999-09-18', 'alamat' => 'Jl.permata bunda 5, blok I12A no.41. Kotabaru, Karawang' , 'contact' => '087781610010' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '17', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '42', 'foto' =>	'default-avatar.png', 'np_user' => 'I425'	, 'nama' => 'Dewi Pertiwi' , 'email' => 'dewiper26@gmail.com' , 'tgl_lahir' => '1998-05-11', 'alamat' => 'Perum Karawang Baru blok A 11 no 15' , 'contact' => '085811347375' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '43', 'foto' =>	'default-avatar.png', 'np_user' => 'I426'	, 'nama' => 'Dini Andini' , 'email' => 'dini@gmail.com' , 'tgl_lahir' => '1998-06-08', 'alamat' => 'Perum Griya Indah Gang Kostrad Blok I 1 NO.3' , 'contact' => '089624263667' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()], 
['id' => '44', 'foto' =>	'default-avatar.png', 'np_user' => 'I428'	, 'nama' => 'Gusti Arifiyanto' , 'email' => 'uti.arifiyanto@gmail.com' , 'tgl_lahir' => '1997-08-06', 'alamat' => 'Perumahan KGV 2  ' , 'contact' => '087773311939 / 089618926881  ' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()], 
['id' => '45', 'foto' =>	'default-avatar.png', 'np_user' => 'I429'	, 'nama' => 'Haina Apriliani' , 'email' => 'Hainaapriliani@gmail.com' , 'tgl_lahir' => '1999-04-17', 'alamat' => 'Perum Bintang Alam blok N2/09 Rt40 Rw11 kec. Teluk Jambe Timur' , 'contact' => '081282430649' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '46', 'foto' =>	'default-avatar.png', 'np_user' => 'I430'	, 'nama' => 'Hermansyah' , 'email' => 'hermansyah5499@gmail.com' , 'tgl_lahir' => '1999-04-05', 'alamat' => 'Perumahan kgv 2  ' , 'contact' => '085865966702' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()], 
['id' => '47', 'foto' =>	'default-avatar.png', 'np_user' => 'I431'	, 'nama' => 'Iis Kurnia' , 'email' => 'iiskurnia10@gmail.com' , 'tgl_lahir' => '1997-02-18', 'alamat' => 'Dusun Pasirtalaga 1 Rt.03/01 Desa Pasirtalaga Kecamatan Telagasari Kab. Karawang 41381  ' , 'contact' => '085779249788' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '48', 'foto' =>	'default-avatar.png', 'np_user' => 'I432'	, 'nama' => 'Julpi Abdul  Muti' , 'email' => 'Julpiabdulmuti8@gmail.com' , 'tgl_lahir' => '1996-09-27', 'alamat' => 'Perum kgv2 ' , 'contact' => '085211213322' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '49', 'foto' =>	'default-avatar.png', 'np_user' => 'I434'	, 'nama' => 'Muhamad Rifki' , 'email' => 'rifkimuhamad752@gmail.com' , 'tgl_lahir' => '1996-06-02', 'alamat' => 'Dusun Sukajaya 02 rt 015 rw 005 Kel. Pinayungan Kec. Telukjambe timur' , 'contact' => '081384812460' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '11', 'updated_at' => now(), 'created_at' => now()],  
['id' => '50', 'foto' =>	'default-avatar.png', 'np_user' => 'I437'	, 'nama' => 'Nuraida Diah W' , 'email' => 'nuraidadiah@gmail.com' , 'tgl_lahir' => '1995-12-12', 'alamat' => ' ' , 'contact' => '085770011531' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '51', 'foto' =>	'default-avatar.png', 'np_user' => 'I440'	, 'nama' => 'Siska Kusuma Wardani' , 'email' => 'siskakw2@gmail.com' , 'tgl_lahir' => '1999-05-24', 'alamat' => 'Kp.Pebayuran 005/002 Kertasari Pebayuran Kab.Bekasi ' , 'contact' => '085717776401' , 'id_seksi' => '1', 'id_unit' => '1', 'id_station' => '13', 'updated_at' => now(), 'created_at' => now()],
['id' => '52', 'foto' =>	'default-avatar.png', 'np_user' => 'I441'	, 'nama' => 'Sofia Nurrahayu' , 'email' => 'sofianurrahayu90@gmail.con' , 'tgl_lahir' => '1999-11-22', 'alamat' => 'Dusun Sukadana Rt 03 Rw 01, No. 92 , Pinayungan , Telukjambe Timur  ' , 'contact' => '081373871789' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],  
['id' => '53', 'foto' =>	'default-avatar.png', 'np_user' => 'I442'	, 'nama' => 'Tri Banda Rahayu' , 'email' => 'trirahayu24799@gmail.com' , 'tgl_lahir' => '1999-07-24', 'alamat' => 'Perumahan Griya Indah Ds. Parungmulya Kec. Ciampel Karawang Jawa Barat ' , 'contact' => '089634250484' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '19', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '54', 'foto' =>	'default-avatar.png', 'np_user' => 'I444'	, 'nama' => 'Zulfikar Hidayatullah' , 'email' => 'vikiryan0@gmail.com' , 'tgl_lahir' => '1999-05-20', 'alamat' => 'Perumnas Bumi Teluk Jambe, Blok S.401, Kec Sukalauyu Teluk Jambe Timur Karawang ' , 'contact' => '081316461691' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '24', 'updated_at' => now(), 'created_at' => now()],
['id' => '55', 'foto' =>	'default-avatar.png', 'np_user' => 'admin'	, 'nama' => 'Admin' , 'email' => 'admin' , 'tgl_lahir' => '1999-05-20', 'alamat' => 'Perumnas Bumi Teluk Jambe, Blok S.401, Kec Sukalauyu Teluk Jambe Timur Karawang ' , 'contact' => '081316461691' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '8 ', 'updated_at' => now(), 'created_at' => now()],
['id' => '56', 'foto' =>	'default-avatar.png', 'np_user' => 'I704'	, 'nama' => 'Roy kenae Junianta' , 'email' => 'roy@gmail.com' , 'tgl_lahir' => '2022-02-03', 'alamat' => 'karawang' , 'contact' => '012345678' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '57', 'foto' =>	'default-avatar.png', 'np_user' => 'I724'	, 'nama' => 'Indra Putra Riyanto' , 'email' => 'indra@gmail.com' , 'tgl_lahir' => '2022-02-03', 'alamat' => 'karawang' , 'contact' => '0812345678' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '58', 'foto' =>	'default-avatar.png', 'np_user' => 'H071'	, 'nama' => 'Adithya Indra' , 'email' => 'a' , 'tgl_lahir' => '2022-02-17', 'alamat' => 'a' , 'contact' => '123456' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '59', 'foto' =>	'default-avatar.png', 'np_user' => 'G834'	, 'nama' => 'Winda Ristika Ratu' , 'email' => 'a' , 'tgl_lahir' => '2021-12-31', 'alamat' => 'a' , 'contact' => '1234' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '60', 'foto' =>	'default-avatar.png', 'np_user' => 'G840'	, 'nama' => 'Siti Masitoh' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '61', 'foto' =>	'default-avatar.png', 'np_user' => 'G715'	, 'nama' => 'Abudzar Al Ghifari' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '123 ' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '62', 'foto' =>	'default-avatar.png', 'np_user' => 'G849'	, 'nama' => 'Siti Masitoh' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '12345' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '63', 'foto' =>	'default-avatar.png', 'np_user' => 'H028'	, 'nama' => 'Khanza Sukma S.' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '123456' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '64', 'foto' =>	'default-avatar.png', 'np_user' => 'H195'	, 'nama' => 'Lulu Dwi Fauziyyah' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],	 
['id' => '65', 'foto' =>	'default-avatar.png', 'np_user' => 'I435'	, 'nama' => 'Nova Rahmatyastuti' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => 'a ' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '66', 'foto' =>	'default-avatar.png', 'np_user' => 'G841'	, 'nama' => 'Desy Nurfitria H.' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '67', 'foto' =>	'default-avatar.png', 'np_user' => 'H200'	, 'nama' => 'Putri Elmia Devi' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '68', 'foto' =>	'default-avatar.png', 'np_user' => 'I411'	, 'nama' => 'Nafisah Ulfi Fauziyah' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '123456' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],  
['id' => '69', 'foto' =>	'default-avatar.png', 'np_user' => 'I412'	, 'nama' => 'Nur Rahma Alifah' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '70', 'foto' =>	'default-avatar.png', 'np_user' => 'I417'	, 'nama' => 'Devi Mardiana' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '123456' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()], 
['id' => '71', 'foto' =>	'default-avatar.png', 'np_user' => 'I419'	, 'nama' => 'Adinda Putri Sabila' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '72', 'foto' =>	'default-avatar.png', 'np_user' => 'I427'	, 'nama' => 'Fauzan Egi Pratomo' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '73', 'foto' =>	'default-avatar.png', 'np_user' => 'I433'	, 'nama' => 'Marfiana Defi Sari' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],
['id' => '74', 'foto' =>	'default-avatar.png', 'np_user' => 'I439'	, 'nama' => 'Rizky Alfani' , 'email' => 'a' , 'tgl_lahir' => '2022-12-31', 'alamat' => 'a' , 'contact' => '1234567' , 'id_seksi' => '2', 'id_unit' => '4', 'id_station' => '18', 'updated_at' => now(), 'created_at' => now()],

  ];

  foreach($profile as $prf){
profile::create($prf);
  }
 }
}
